[workspace]
members = [ "crates/telegrab-model", "crates/telegrab-db", "crates/telegrab-core", "crates/telegrab", "crates/telegrabber" ]
resolver = "2"

[workspace.package]
version = "0.2.0"
edition = "2024"
authors = ["Jonir Rings <i@jonirrings.com>"]

[profile.release]
lto = "thin"
opt-level = "z"
strip = true
panic = "abort"

[profile.dev]
opt-level = 0
debug = 2
incremental = true
