-- Add migration script here
create table doc
(
    id               serial primary key,
    url              text      not null unique,
    page_title       text,
    page_date        timestamptz,
    title            text,
    series           text,
    number           text,
    count            text,
    volume           text,
    summary          text,
    notes            text,
    year             int,
    month            int,
    day              int,
    writer           text,
    penciller        text,
    inker            text,
    colorist         text,
    letterer         text,
    cover_artist     text,
    editor           text,
    publisher        text,
    imprint          text,
    genre            text,
    tags             text,
    web              text,
    page_count       text,
    language         text,
    format           text,
    black_and_white  bool,
    characters       text,
    teams            text,
    locations        text,
    scan_information text,
    story_arc        text,
    series_group     text,
    age_rating       text,
    community_rating text,
    critical_rating  text,
    created_at       timestamptz not null default now(),
    updated_at       timestamptz not null default now()
);