[package]
name = "telegrabber"
version = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }
description = "Standalone CLI to fetch telegra.ph pages and archive as CBZ"

[[bin]]
name = "telegrabber"
path = "src/main.rs"

[dependencies]
telegrab-core = { path = "../telegrab-core" }
telegrab-model = { path = "../telegrab-model" }
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
anyhow = { workspace = true }
time = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }
