application:
  port: 9000
database:
  host: "localhost"
  port: 5432
  username: "telegrab"
  password: "password"
  database_name: "telegrab"
redis_uri: "redis://localhost:6379"
http_client:
  connect_timeout_secs: 30
  timeout_secs: 60
  max_connections: 100
  pool_enabled: true
  user_agent: "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/145.0.0.0 Safari/537.36 Edg/145.0.0.0"
worker:
  count: 4
  max_completed_tasks: 100
  auto_cleanup_interval_secs: 60
data_dir: "data"
logger:
  # Enable pretty backtrace (sets RUST_BACKTRACE=1)
  pretty_backtrace: true
  # Log level, options: trace, debug, info, warn or error.
  level: info
  # Define the logging format. options: compact, pretty or json
  format: pretty
