application:
  port: 9000
database:
  host: "localhost"
  port: 5432
  username: "telegrab"
  password: "password"
  database_name: "telegrab"
redis_uri: "redis://localhost:6379"
logger:
  # Enable pretty backtrace (sets RUST_BACKTRACE=1)
  pretty_backtrace: true
  # Log level, options: trace, debug, info, warn or error.
  level: debug
  # Define the logging format. options: compact, pretty or json
  format: pretty
