application:
  base_url: "http://127.0.0.1:9000"

database:
  host: "/var/run/postgresql"
  database_name: "telegrab"
  # with UNIX domain socket, the following options are ignored
  port: 5432
  username: "telegrab"
  password: "password"
  require_ssl: false
